### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'os/iso/hypercube_os_bios.iso'

### ISSUE THREAD

**Issue by AURORA1325** [RUB-SysSec/Hypercube#1]
Hello, it is an amaizing work! I was very interested in it, and I encountered some problems when I wanted to reproduce the work.  I hope to get your advice.
When I execute the command ` python3 hypercube.py generate /tmp/vga.iso --enable_pci --filter “VGA” `  to generate an OS image for the VGA device emulator, I encountered the following error:
```
root@3a1da2e98dcb:~/Hypercube# python3 hypercube.py generate /tmp/vga.iso --enable_pci --filter "VGA"
[*] Generated configuration:
--------------------------------------------------
#pragma once

#define ENABLE_TTY_SERIAL
#define EARLY_BOOT_PRINTF
#define PCI_FUZZING

#define TARGET_FILTERS char* target_filters[] = {\
    "VGA",\
};
--------------------------------------------------
[*] Compiling hypercube image (BIOS)...
[*] Moving image to /tmp/vga.iso
Traceback (most recent call last):
  File "/usr/lib/python3.6/shutil.py", line 550, in move
    os.rename(src, real_dst)
FileNotFoundError: [Errno 2] No such file or directory: 'os/iso/hypercube_os_bios.iso' -> '/tmp/vga.iso'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "hypercube.py", line 9, in <module>
    main()
  File "/root/Hypercube/scripts/main.py", line 53, in main
    handle_generate(parser, args)
  File "/root/Hypercube/scripts/main.py", line 41, in handle_generate
    build_hypercube_image(configuration, path=args.image_dest, uefi=args.uefi)
  File "/root/Hypercube/scripts/compile.py", line 161, in build_hypercube_image
    shutil.move("os/iso/hypercube_os_bios.iso", path)
  File "/usr/lib/python3.6/shutil.py", line 564, in move
    copy_function(src, real_dst)
  File "/usr/lib/python3.6/shutil.py", line 263, in copy2
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/usr/lib/python3.6/shutil.py", line 120, in copyfile
    with open(src, 'rb') as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: 'os/iso/hypercube_os_bios.iso'
```
What should I do? Looking forward to your response.

Thanks again for your work.

**Comment by schumilo** [comment]
It seems that the OS image was not generated for some reason. Did you use the `setup.sh` script before running the python code?

**Comment by AURORA1325** [comment]
Thank you for your reply. I've used the `setup.sh` script before running the python code. It seems the setup is all right , but the `python3 hypercube.py generate /tmp/vga.iso --enable_pci --filter "VGA"` is cannot work. And the following is the information of `setup.sh`
```
root@3a1da2e98dcb:~/Hypercube# ./setup.sh
[!] Installing required dependencies...
Hit:1 http://archive.ubuntu.com/ubuntu bionic InRelease                  
Get:2 http://archive.ubuntu.com/ubuntu bionic-updates InRelease [88.7 kB]                              
Get:3 http://security.ubuntu.com/ubuntu bionic-security InRelease [88.7 kB]
Get:4 http://archive.ubuntu.com/ubuntu bionic-backports InRelease [83.3 kB]
Fetched 261 kB in 13s (20.7 kB/s)                                                                               
Reading package lists... Done
Reading package lists... Done
Building dependency tree       
Reading state information... Done
autoconf is already the newest version (2.69-11).
automake is already the newest version (1:1.15.1-3ubuntu2).
bash-completion is already the newest version (1:2.8-1ubuntu1).
bison is already the newest version (2:3.0.4.dfsg-1build1).
dh-autoreconf is already the newest version (17).
dosfstools is already the newest version (4.1-1).
flex is already the newest version (2.6.4-6).
fonts-dejavu-core is already the newest version (2.37-1).
libefivar-dev is already the newest version (34-1).
libfuse-dev is already the newest version (2.9.7-1ubuntu1).
liblzo2-dev is already the newest version (2.08-1.2).
libxen-dev is already the newest version (4.9.2-0ubuntu1).
make is already the newest version (4.1-9.1ubuntu1).
mtools is already the newest version (4.0.18-2ubuntu1).
patchutils is already the newest version (0.3.4-2).
pkg-config is already the newest version (0.29.1-0ubuntu2).
po-debconf is already the newest version (1.0.20).
python is already the newest version (2.7.15~rc1-1).
unifont is already the newest version (1:10.0.07-1).
wamerican is already the newest version (2017.08.24-1).
xfonts-unifont is already the newest version (1:10.0.07-1).
gcc-5 is already the newest version (5.5.0-12ubuntu1).
gcc-5-multilib is already the newest version (5.5.0-12ubuntu1).
help2man is already the newest version (1.47.6).
libisoburn1 is already the newest version (1.4.8-3).
texinfo is already the newest version (6.5.0.dfsg.1-2).
ttf-dejavu-core is already the newest version (2.37-1).
xorriso is already the newest version (1.4.8-3).
cpio is already the newest version (2.12+dfsg-6ubuntu0.18.04.4).
debhelper is already the newest version (11.1.6ubuntu2).
g++-multilib is already the newest version (4:7.4.0-1ubuntu2.3).
gcc is already the newest version (4:7.4.0-1ubuntu2.3).
gettext is already the newest version (0.19.8.1-6ubuntu0.3).
libdevmapper-dev is already the newest version (2:1.02.145-4.1ubuntu3.18.04.3).
libfreetype6-dev is already the newest version (2.8.1-2ubuntu2.2).
libglib2.0-dev is already the newest version (2.56.4-0ubuntu0.18.04.9).
liblzma-dev is already the newest version (5.2.2-1.3ubuntu0.1).
libparted-dev is already the newest version (3.2-20ubuntu0.2).
libsdl1.2-dev is already the newest version (1.2.15+dfsg2-0.1ubuntu0.2).
parted is already the newest version (3.2-20ubuntu0.2).
python3 is already the newest version (3.6.7-1~18.04).
python3-dev is already the newest version (3.6.7-1~18.04).
zlib1g-dev is already the newest version (1:1.2.11.dfsg-0ubuntu2.2).
dh-systemd is already the newest version (11.1.6ubuntu2).
qemu-system is already the newest version (1:2.11+dfsg-1ubuntu7.42).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
--2023-08-17 04:15:24--  https://bootstrap.pypa.io/pip/3.5/get-pip.py
Resolving bootstrap.pypa.io (bootstrap.pypa.io)... 146.75.112.175, 2a04:4e42:8c::175
Connecting to bootstrap.pypa.io (bootstrap.pypa.io)|146.75.112.175|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1908223 (1.8M) [text/x-python]
Saving to: 'get-pip.py.3'

get-pip.py.3                 100%[===========================================>]   1.82M  30.0KB/s    in 70s     

2023-08-17 04:16:40 (26.5 KB/s) - 'get-pip.py.3' saved [1908223/1908223]

/usr/local/lib/python3.6/dist-packages/setuptools/command/install.py:37: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
  setuptools.SetuptoolsDeprecationWarning,
Collecting pip<21.0
  Using cached pip-20.3.4-py2.py3-none-any.whl (1.5 MB)
Installing collected packages: pip
  Attempting uninstall: pip
    Found existing installation: pip 20.3.4
    Uninstalling pip-20.3.4:
      Successfully uninstalled pip-20.3.4
/usr/local/lib/python3.6/dist-packages/setuptools/command/install.py:37: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
  setuptools.SetuptoolsDeprecationWarning,
/usr/local/lib/python3.6/dist-packages/setuptools/command/install.py:37: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
  setuptools.SetuptoolsDeprecationWarning,
Successfully installed pip-20.3.4
WARNING: You are using pip version 20.3.4; however, version 21.3.1 is available.
You should consider upgrading via the '/usr/bin/python3 -m pip install --upgrade pip' command.
/root/Hypercube
/root/Hypercube
running install
/usr/local/lib/python3.6/dist-packages/setuptools/command/install.py:37: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
  setuptools.SetuptoolsDeprecationWarning,
/usr/local/lib/python3.6/dist-packages/setuptools/command/easy_install.py:159: EasyInstallDeprecationWarning: easy_install command is deprecated. Use build and pip and other standards-based tools.
  EasyInstallDeprecationWarning,
running bdist_egg
running egg_info
writing python_ptrace.egg-info/PKG-INFO
writing dependency_links to python_ptrace.egg-info/dependency_links.txt
writing top-level names to python_ptrace.egg-info/top_level.txt
reading manifest file 'python_ptrace.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no files found matching 'AUTHORS'
warning: no files found matching 'ChangeLog'
warning: no files found matching 'INSTALL'
warning: no files found matching 'README.cptrace'
warning: no files found matching 'TODO'
warning: no files found matching 'pyflakes.sh'
warning: no files found matching 'python3.0.patch'
adding license file 'COPYING'
writing manifest file 'python_ptrace.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
creating build/bdist.linux-x86_64/egg
creating build/bdist.linux-x86_64/egg/ptrace
copying build/lib/ptrace/mockup.py -> build/bdist.linux-x86_64/egg/ptrace
copying build/lib/ptrace/version.py -> build/bdist.linux-x86_64/egg/ptrace
copying build/lib/ptrace/process_tools.py -> build/bdist.linux-x86_64/egg/ptrace
copying build/lib/ptrace/ctypes_libc.py -> build/bdist.linux-x86_64/egg/ptrace
copying build/lib/ptrace/ctypes_tools.py -> build/bdist.linux-x86_64/egg/ptrace
copying build/lib/ptrace/logging_tools.py -> build/bdist.linux-x86_64/egg/ptrace
creating build/bdist.linux-x86_64/egg/ptrace/syscall
copying build/lib/ptrace/syscall/freebsd_syscall.py -> build/bdist.linux-x86_64/egg/ptrace/syscall
copying build/lib/ptrace/syscall/syscall_argument.py -> build/bdist.linux-x86_64/egg/ptrace/syscall
copying build/lib/ptrace/syscall/freebsd_constants.py -> build/bdist.linux-x86_64/egg/ptrace/syscall
copying build/lib/ptrace/syscall/prototypes.py -> build/bdist.linux-x86_64/egg/ptrace/syscall
copying build/lib/ptrace/syscall/names.py -> build/bdist.linux-x86_64/egg/ptrace/syscall
copying build/lib/ptrace/syscall/socketcall_struct.py -> build/bdist.linux-x86_64/egg/ptrace/syscall
copying build/lib/ptrace/syscall/linux_constants.py -> build/bdist.linux-x86_64/egg/ptrace/syscall
copying build/lib/ptrace/syscall/posix_constants.py -> build/bdist.linux-x86_64/egg/ptrace/syscall
copying build/lib/ptrace/syscall/linux_struct.py -> build/bdist.linux-x86_64/egg/ptrace/syscall
copying build/lib/ptrace/syscall/__init__.py -> build/bdist.linux-x86_64/egg/ptrace/syscall
copying build/lib/ptrace/syscall/posix_arg.py -> build/bdist.linux-x86_64/egg/ptrace/syscall
copying build/lib/ptrace/syscall/socketcall_constants.py -> build/bdist.linux-x86_64/egg/ptrace/syscall
creating build/bdist.linux-x86_64/egg/ptrace/syscall/linux
copying build/lib/ptrace/syscall/linux/x86_64.py -> build/bdist.linux-x86_64/egg/ptrace/syscall/linux
copying build/lib/ptrace/syscall/linux/powerpc64.py -> build/bdist.linux-x86_64/egg/ptrace/syscall/linux
copying build/lib/ptrace/syscall/linux/__init__.py -> build/bdist.linux-x86_64/egg/ptrace/syscall/linux
copying build/lib/ptrace/syscall/linux/i386.py -> build/bdist.linux-x86_64/egg/ptrace/syscall/linux
copying build/lib/ptrace/syscall/linux/riscv64.py -> build/bdist.linux-x86_64/egg/ptrace/syscall/linux
copying build/lib/ptrace/syscall/linux/powerpc32.py -> build/bdist.linux-x86_64/egg/ptrace/syscall/linux
copying build/lib/ptrace/syscall/linux/aarch64.py -> build/bdist.linux-x86_64/egg/ptrace/syscall/linux
copying build/lib/ptrace/syscall/linux/riscv32.py -> build/bdist.linux-x86_64/egg/ptrace/syscall/linux
copying build/lib/ptrace/syscall/socketcall.py -> build/bdist.linux-x86_64/egg/ptrace/syscall
copying build/lib/ptrace/syscall/ptrace_syscall.py -> build/bdist.linux-x86_64/egg/ptrace/syscall
copying build/lib/ptrace/os_tools.py -> build/bdist.linux-x86_64/egg/ptrace
copying build/lib/ptrace/signames.py -> build/bdist.linux-x86_64/egg/ptrace
creating build/bdist.linux-x86_64/egg/ptrace/binding
copying build/lib/ptrace/binding/openbsd_struct.py -> build/bdist.linux-x86_64/egg/ptrace/binding
copying build/lib/ptrace/binding/func.py -> build/bdist.linux-x86_64/egg/ptrace/binding
copying build/lib/ptrace/binding/linux_struct.py -> build/bdist.linux-x86_64/egg/ptrace/binding
copying build/lib/ptrace/binding/__init__.py -> build/bdist.linux-x86_64/egg/ptrace/binding
copying build/lib/ptrace/binding/cpu.py -> build/bdist.linux-x86_64/egg/ptrace/binding
copying build/lib/ptrace/binding/freebsd_struct.py -> build/bdist.linux-x86_64/egg/ptrace/binding
copying build/lib/ptrace/terminal.py -> build/bdist.linux-x86_64/egg/ptrace
copying build/lib/ptrace/linux_proc.py -> build/bdist.linux-x86_64/egg/ptrace
copying build/lib/ptrace/func_call.py -> build/bdist.linux-x86_64/egg/ptrace
copying build/lib/ptrace/pydistorm.py -> build/bdist.linux-x86_64/egg/ptrace
copying build/lib/ptrace/__init__.py -> build/bdist.linux-x86_64/egg/ptrace
copying build/lib/ptrace/error.py -> build/bdist.linux-x86_64/egg/ptrace
creating build/bdist.linux-x86_64/egg/ptrace/debugger
copying build/lib/ptrace/debugger/syscall_state.py -> build/bdist.linux-x86_64/egg/ptrace/debugger
copying build/lib/ptrace/debugger/signal_reason.py -> build/bdist.linux-x86_64/egg/ptrace/debugger
copying build/lib/ptrace/debugger/ptrace_signal.py -> build/bdist.linux-x86_64/egg/ptrace/debugger
copying build/lib/ptrace/debugger/process.py -> build/bdist.linux-x86_64/egg/ptrace/debugger
copying build/lib/ptrace/debugger/process_error.py -> build/bdist.linux-x86_64/egg/ptrace/debugger
copying build/lib/ptrace/debugger/backtrace.py -> build/bdist.linux-x86_64/egg/ptrace/debugger
copying build/lib/ptrace/debugger/__init__.py -> build/bdist.linux-x86_64/egg/ptrace/debugger
copying build/lib/ptrace/debugger/parse_expr.py -> build/bdist.linux-x86_64/egg/ptrace/debugger
copying build/lib/ptrace/debugger/application.py -> build/bdist.linux-x86_64/egg/ptrace/debugger
copying build/lib/ptrace/debugger/process_event.py -> build/bdist.linux-x86_64/egg/ptrace/debugger
copying build/lib/ptrace/debugger/memory_mapping.py -> build/bdist.linux-x86_64/egg/ptrace/debugger
copying build/lib/ptrace/debugger/child.py -> build/bdist.linux-x86_64/egg/ptrace/debugger
copying build/lib/ptrace/debugger/breakpoint.py -> build/bdist.linux-x86_64/egg/ptrace/debugger
copying build/lib/ptrace/debugger/debugger.py -> build/bdist.linux-x86_64/egg/ptrace/debugger
copying build/lib/ptrace/cpu_info.py -> build/bdist.linux-x86_64/egg/ptrace
copying build/lib/ptrace/tools.py -> build/bdist.linux-x86_64/egg/ptrace
copying build/lib/ptrace/func_arg.py -> build/bdist.linux-x86_64/egg/ptrace
copying build/lib/ptrace/profiler.py -> build/bdist.linux-x86_64/egg/ptrace
copying build/lib/ptrace/disasm.py -> build/bdist.linux-x86_64/egg/ptrace
byte-compiling build/bdist.linux-x86_64/egg/ptrace/mockup.py to mockup.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/ptrace/version.py to version.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/ptrace/process_tools.py to process_tools.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/ptrace/ctypes_libc.py to ctypes_libc.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/ptrace/ctypes_tools.py to ctypes_tools.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/ptrace/logging_tools.py to logging_tools.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/ptrace/syscall/freebsd_syscall.py to freebsd_syscall.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/ptrace/syscall/syscall_argument.py to syscall_argument.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/ptrace/syscall/freebsd_constants.py to freebsd_constants.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/ptrace/syscall/prototypes.py to prototypes.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/ptrace/syscall/names.py to names.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/ptrace/syscall/socketcall_struct.py to socketcall_struct.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/ptrace/syscall/linux_constants.py to linux_constants.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/ptrace/syscall/posix_constants.py to posix_constants.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/ptrace/syscall/linux_struct.py to linux_struct.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/ptrace/syscall/__init__.py to __init__.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/ptrace/syscall/posix_arg.py to posix_arg.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/ptrace/syscall/socketcall_constants.py to socketcall_constants.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/ptrace/syscall/linux/x86_64.py to x86_64.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/ptrace/syscall/linux/powerpc64.py to powerpc64.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/ptrace/syscall/linux/__init__.py to __init__.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/ptrace/syscall/linux/i386.py to i386.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/ptrace/syscall/linux/riscv64.py to riscv64.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/ptrace/syscall/linux/powerpc32.py to powerpc32.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/ptrace/syscall/linux/aarch64.py to aarch64.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/ptrace/syscall/linux/riscv32.py to riscv32.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/ptrace/syscall/socketcall.py to socketcall.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/ptrace/syscall/ptrace_syscall.py to ptrace_syscall.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/ptrace/os_tools.py to os_tools.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/ptrace/signames.py to signames.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/ptrace/binding/openbsd_struct.py to openbsd_struct.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/ptrace/binding/func.py to func.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/ptrace/binding/linux_struct.py to linux_struct.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/ptrace/binding/__init__.py to __init__.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/ptrace/binding/cpu.py to cpu.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/ptrace/binding/freebsd_struct.py to freebsd_struct.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/ptrace/terminal.py to terminal.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/ptrace/linux_proc.py to linux_proc.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/ptrace/func_call.py to func_call.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/ptrace/pydistorm.py to pydistorm.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/ptrace/__init__.py to __init__.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/ptrace/error.py to error.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/ptrace/debugger/syscall_state.py to syscall_state.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/ptrace/debugger/signal_reason.py to signal_reason.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/ptrace/debugger/ptrace_signal.py to ptrace_signal.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/ptrace/debugger/process.py to process.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/ptrace/debugger/process_error.py to process_error.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/ptrace/debugger/backtrace.py to backtrace.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/ptrace/debugger/__init__.py to __init__.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/ptrace/debugger/parse_expr.py to parse_expr.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/ptrace/debugger/application.py to application.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/ptrace/debugger/process_event.py to process_event.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/ptrace/debugger/memory_mapping.py to memory_mapping.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/ptrace/debugger/child.py to child.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/ptrace/debugger/breakpoint.py to breakpoint.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/ptrace/debugger/debugger.py to debugger.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/ptrace/cpu_info.py to cpu_info.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/ptrace/tools.py to tools.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/ptrace/func_arg.py to func_arg.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/ptrace/profiler.py to profiler.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/ptrace/disasm.py to disasm.cpython-36.pyc
creating build/bdist.linux-x86_64/egg/EGG-INFO
installing scripts to build/bdist.linux-x86_64/egg/EGG-INFO/scripts
running install_scripts
running build_scripts
creating build/bdist.linux-x86_64/egg/EGG-INFO/scripts
copying build/scripts-3.6/strace.py -> build/bdist.linux-x86_64/egg/EGG-INFO/scripts
copying build/scripts-3.6/gdb.py -> build/bdist.linux-x86_64/egg/EGG-INFO/scripts
changing mode of build/bdist.linux-x86_64/egg/EGG-INFO/scripts/strace.py to 755
changing mode of build/bdist.linux-x86_64/egg/EGG-INFO/scripts/gdb.py to 755
copying python_ptrace.egg-info/PKG-INFO -> build/bdist.linux-x86_64/egg/EGG-INFO
copying python_ptrace.egg-info/SOURCES.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying python_ptrace.egg-info/dependency_links.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying python_ptrace.egg-info/top_level.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
zip_safe flag not set; analyzing archive contents...
creating 'dist/python_ptrace-0.9.9-py3.6.egg' and adding 'build/bdist.linux-x86_64/egg' to it
removing 'build/bdist.linux-x86_64/egg' (and everything under it)
Processing python_ptrace-0.9.9-py3.6.egg
Removing /usr/local/lib/python3.6/dist-packages/python_ptrace-0.9.9-py3.6.egg
Copying python_ptrace-0.9.9-py3.6.egg to /usr/local/lib/python3.6/dist-packages
python-ptrace 0.9.9 is already the active version in easy-install.pth
Installing gdb.py script to /usr/local/bin
Installing strace.py script to /usr/local/bin

Installed /usr/local/lib/python3.6/dist-packages/python_ptrace-0.9.9-py3.6.egg
Processing dependencies for python-ptrace==0.9.9
Finished processing dependencies for python-ptrace==0.9.9
/root/Hypercube
Reading package lists... Done
Building dependency tree       
Reading state information... Done
ninja-build is already the newest version (1.8.2-1).
libpixman-1-dev is already the newest version (0.34.0-2ubuntu0.1).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Requirement already satisfied: psutil in /usr/local/lib/python3.6/dist-packages (5.9.5)
WARNING: You are using pip version 20.3.4; however, version 21.3.1 is available.
You should consider upgrading via the '/usr/bin/python3 -m pip install --upgrade pip' command.
[*] Downloading GRUB2 2.02 ...
[*] Checking signature of GRUB2 2.02 ...
[*] Unpacking GRUB2 2.02 ...
rm: cannot remove './compile-bios.stdout': No such file or directory
rm: cannot remove './compile-bios.stderr': No such file or directory
[*] Compiling GRUB2 2.02 BIOS bootloader ...
rm: cannot remove './compile-efi.stdout': No such file or directory
rm: cannot remove './compile-efi.stderr': No such file or directory
[*] Compiling GRUB2 2.02 EFI bootloader ...
rm: cannot remove './compile-efi-app.stdout': No such file or directory
rm: cannot remove './compile-efi-app.stderr': No such file or directory
[*] Compiling GRUB2 2.02 EFI-APP bootloader ...
patching file grub-2.02/grub-core/video/video.c
patching file grub-2.02/grub-core/loader/multiboot.c
patching file grub-2.02/grub-core/kern/efi/mm.c
[*] Done ...
/root/Hypercube
/root/Hypercube
/root/Hypercube
[!] Setup finished!
```
Then , if I execute the command ` python3 hypercube.py generate /tmp/vga.iso --enable_pci --filter "VGA"`, the erro information  is `FileNotFoundError: [Errno 2] No such file or directory: 'os/iso/hypercube_os_bios.iso'` , just like the above information

```
root@3a1da2e98dcb:~/Hypercube# python3 hypercube.py generate /tmp/vga.iso --enable_pci --filter "VGA"
[*] Generated configuration:
--------------------------------------------------
#pragma once

#define ENABLE_TTY_SERIAL
#define EARLY_BOOT_PRINTF
#define PCI_FUZZING

#define TARGET_FILTERS char* target_filters[] = {\
    "VGA",\
};
--------------------------------------------------
[*] Compiling hypercube image (BIOS)...
[*] Moving image to /tmp/vga.iso
Traceback (most recent call last):
  File "/usr/lib/python3.6/shutil.py", line 550, in move
    os.rename(src, real_dst)
FileNotFoundError: [Errno 2] No such file or directory: 'os/iso/hypercube_os_bios.iso' -> '/tmp/vga.iso'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "hypercube.py", line 9, in <module>
    main()
  File "/root/Hypercube/scripts/main.py", line 53, in main
    handle_generate(parser, args)
  File "/root/Hypercube/scripts/main.py", line 41, in handle_generate
    build_hypercube_image(configuration, path=args.image_dest, uefi=args.uefi)
  File "/root/Hypercube/scripts/compile.py", line 161, in build_hypercube_image
    shutil.move("os/iso/hypercube_os_bios.iso", path)
  File "/usr/lib/python3.6/shutil.py", line 564, in move
    copy_function(src, real_dst)
  File "/usr/lib/python3.6/shutil.py", line 263, in copy2
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/usr/lib/python3.6/shutil.py", line 120, in copyfile
    with open(src, 'rb') as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: 'os/iso/hypercube_os_bios.iso'
```
What should I do anything else ?  Looking forward to your response.
Thank you again!

**Comment by schumilo** [comment]
Could you please check if the `os/iso` directory actually exists? And if not, please try to create directory first and then run the python command again. Maybe this will fix the issue...

**Comment by AURORA1325** [comment]
Thank you! It works! Thanks again for your reply!
